//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseStudy_PNA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFood
    {
        public int Id_PK { get; set; }
        public string DishName { get; set; }
        public string Cuisine { get; set; }
        public int Price { get; set; }
        public int Discount { get; set; }
    }
}
